version: '3.0'

services:
    php:
        container_name: topiccards_php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: strehle-de/topiccards-php
        volumes:
            - ./app:/opt/app
            - ./docker/php/zz-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        hostname: web
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./app:/opt/app
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
